import Image from 'next/image';
import FeedbackForm from '../components/FeedbackForm';
import GsapReveal from '../components/GsapReveal';
import MapEmbed from '../components/MapEmbed';
import OrderForm from '../components/OrderForm';
import ProductGallery from '../components/ProductGallery';
import ReviewWall from '../components/ReviewWall';

const reviews = [['A', 'Arun Das', 'Patipukur Local', 'Gupta Ji keeps the best bhujia and namkeen in the area. The products are fresh, the service is genuine, and the feeling is always warm and local.'], ['S', 'Shreya Sen', 'Basak Bagan Resident', 'Very reliable shop for daily groceries and household needs. The owner is kind, helpful, and the quality is consistently good.'], ['M', 'Mrityunjoy Roy', 'Local Customer', 'This shop has been in the area for years, and people trust it for a reason. Excellent for snacks, staples, and household essentials.']];

export default function HomePage() { return <main id="home">
  <section className="relative overflow-hidden pb-10 pt-16 md:pt-24"><div className="container-page grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><GsapReveal><div><span className="eyebrow">Serving Patipukur Since 1990</span><h1 className="mt-5 max-w-4xl text-5xl font-extrabold leading-[.98] tracking-[-.06em] md:text-7xl">Trusted <span className="text-leaf dark:text-[#8fe9c3]">Groceries & Bhujiya</span> from <span className="text-gold">Basak Bagan</span></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-slate-600 dark:text-[#adbfba]">For <strong>more than 35 years</strong>, Gupta Variety Store in <strong>Patipukur</strong> has been the local destination for namkeen, snacks, spices, grains, household essentials, and honest neighborhood service.</p><div className="mt-7 flex flex-wrap gap-3"><a href="tel:9007182511" className="btn-primary">📞 Call Store</a><a href="https://wa.me/919007182511?text=Hello%20Gupta%20Variety%20Store%2C%20I%20want%20to%20order%20groceries." className="btn-secondary">💬 WhatsApp Order</a></div><div className="mt-8 flex flex-wrap gap-3">{[['35+ Years', 'Serving since 1990'], ['7 Days', 'Open'], ['Local', 'Trusted']].map(([value, label]) => <div key={value} className="surface min-w-28 rounded-2xl px-4 py-3"><strong className="block text-xl text-leaf dark:text-[#8fe9c3]">{value}</strong><span className="text-xs font-bold text-slate-500 dark:text-[#adbfba]">{label}</span></div>)}</div></div></GsapReveal><GsapReveal delay={.15}><div className="relative"><div className="overflow-hidden rounded-[2.2rem] border border-leaf/10 bg-gradient-to-br from-gold/20 to-mint p-3 shadow-glow"><Image className="h-[430px] w-full rounded-[1.7rem] object-cover md:h-[570px]" src="/shop.jpg" alt="Gupta Variety Store front in Patipukur Kolkata" width={760} height={760} priority /></div><div className="absolute bottom-6 left-6 rounded-xl bg-forest/90 px-4 py-3 text-white shadow-soft backdrop-blur"><strong className="block text-sm">Gupta Ji Bhujiya Wala</strong><span className="text-xs text-white/80">77 Basak Bagan, Patipukur</span></div></div></GsapReveal></div></section>

  <section className="section-pad"><div className="container-page"><GsapReveal><div className="surface grid overflow-hidden lg:grid-cols-[.9fr_1.1fr]"><div className="min-h-[360px] bg-gradient-to-br from-[#d9efe8] to-[#f7e7c6]"><Image className="h-full w-full object-cover" src="/owner-photo.jpg" alt="Shiv Narayan Gupta, owner of Gupta Variety Store" width={720} height={720} /></div><div className="p-8 md:p-12"><span className="eyebrow">Founder Story</span><h2 className="mt-4 text-3xl font-extrabold md:text-5xl">Meet Shiv Narayan Gupta</h2><p className="mt-5 leading-relaxed text-slate-600 dark:text-[#adbfba]"><strong>Gupta Ji Bhujiya Wala</strong> is a beloved name in <strong>Basak Bagan, Patipukur</strong>. Since 1990, Shiv Narayan Gupta has built a reputation for sincerity, quality, and dependable service that families trust every day.</p><p className="mt-4 leading-relaxed text-slate-600 dark:text-[#adbfba]">What began as a neighborhood shop evolved into a trusted local destination for bhujia, namkeen, groceries, household essentials, and everyday family needs.</p><div className="mt-6 flex flex-wrap gap-2">{['Since 1990', '35+ Years Strong', 'Basak Bagan Favorite', 'Trusted Local Shop', 'Family Service'].map((tag) => <span className="rounded-full border border-leaf/10 bg-white px-3 py-2 text-xs font-bold dark:bg-[#1a2d28]" key={tag}>{tag}</span>)}</div></div></div></GsapReveal></div></section>

  <section className="section-pad pt-0"><div className="container-page"><div className="mb-8 text-center"><span className="eyebrow">Advance Payment</span><h2 className="mt-3 text-3xl font-extrabold md:text-5xl">Pay in advance for bulk orders</h2><p className="mx-auto mt-3 max-w-2xl text-slate-600 dark:text-[#adbfba]">Scan the QR code before pickup or delivery, then send the order details on WhatsApp.</p></div><GsapReveal><div className="surface grid overflow-hidden md:grid-cols-[.8fr_1.2fr]"><div className="flex items-center justify-center bg-mint p-8"><Image className="w-full max-w-xs rounded-3xl bg-white p-3 shadow-soft" src="/paytm-QRCode.jpg" alt="Paytm QR code for advance payment" width={500} height={500} /></div><div className="flex flex-col justify-center p-8 md:p-12"><span className="eyebrow w-fit">Secure Payment</span><h3 className="mt-4 text-3xl font-extrabold">Pay by Paytm QR</h3><p className="mt-3 leading-relaxed text-slate-600 dark:text-[#adbfba]">Advance payment for groceries, snacks, or bulk household orders. Please share your name and order details after payment.</p><div className="mt-6 rounded-2xl border border-gold/20 bg-gold/10 p-4 font-bold">📌 Advance payment for bulk orders</div></div></div></GsapReveal></div></section>

  <section className="section-pad bg-white/40 dark:bg-[#121d1a]/40"><div className="container-page"><div className="mb-8 text-center"><span className="eyebrow">Our collection</span><h2 className="mt-3 text-3xl font-extrabold md:text-5xl">Popular store essentials</h2><p className="mx-auto mt-3 max-w-2xl text-slate-600 dark:text-[#adbfba]">Trusted everyday products selected for every household need.</p></div><ProductGallery /></div></section>

  <section className="section-pad" id="gallery"><div className="container-page"><div className="mb-8 text-center"><span className="eyebrow">Store Gallery</span><h2 className="mt-3 text-3xl font-extrabold md:text-5xl">A warm neighborhood feel</h2></div><div className="grid gap-5 md:grid-cols-3">{[['/shop.jpg', 'Store frontage'], ['/owner-photo.jpg', 'Owner Shiv Narayan Gupta'], ['https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80', 'Everyday essentials']].map(([image, caption], index) => <GsapReveal key={caption} delay={index * .1}><figure className="surface group overflow-hidden"><img className="h-64 w-full object-cover transition duration-700 group-hover:scale-105" src={image} alt={caption} /><figcaption className="p-5 font-bold">{caption}</figcaption></figure></GsapReveal>)}</div></div></section>

  <section className="section-pad bg-white/40 dark:bg-[#121d1a]/40" id="reviews"><div className="container-page"><div className="mb-8 text-center"><span className="eyebrow">Customer Reviews</span><h2 className="mt-3 text-3xl font-extrabold md:text-5xl">What the neighborhood says</h2></div><div className="grid gap-5 md:grid-cols-3">{reviews.map(([initial, name, location, quote], index) => <GsapReveal key={name} delay={index * .1}><article className="surface h-full p-6"><div className="text-lg text-gold">★★★★★</div><p className="mt-3 text-slate-600 dark:text-[#adbfba]">“{quote}”</p><div className="mt-5 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-gradient-to-br from-leaf to-gold font-extrabold text-white">{initial}</span><span><strong>{name}</strong><small className="block text-slate-500 dark:text-[#adbfba]">{location}</small></span></div></article></GsapReveal>)}</div><ReviewWall /></div></section>

  <section className="section-pad"><div className="container-page"><OrderForm /></div></section>

  <section className="section-pad" id="contact"><div className="container-page"><div className="mb-8 text-center"><span className="eyebrow">Find us</span><h2 className="mt-3 text-3xl font-extrabold md:text-5xl">Visit Gupta Variety Store</h2><p className="mt-3 text-slate-600 dark:text-[#adbfba]">Simple to locate and easy to reach in Patipukur.</p></div><div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><div className="surface p-7"><h3 className="text-2xl font-extrabold">Store details</h3>{[['Address', '77 Basak Bagan, Patipukur, Kolkata - 700048, West Bengal'], ['Landmark', 'Opposite the Pond'], ['Hours', '7:00 AM – 2:30 PM | 6:00 PM – 11:30 PM'], ['Phone', '+91 9007182511'], ['Payment', 'Cash, UPI, Google Pay, PhonePe, Paytm']].map(([label, value]) => <div className="mt-5" key={label}><div className="text-xs font-extrabold uppercase tracking-wider text-leaf">{label}</div><div className="mt-1 font-semibold">{label === 'Phone' ? <a href="tel:9007182511" className="text-leaf">{value}</a> : value}</div></div>)}</div><div className="surface min-h-[400px] overflow-hidden"><MapEmbed /></div></div><div className="surface mt-6 grid gap-8 bg-mint/50 p-6 md:grid-cols-[.8fr_1.2fr] md:p-10"><div><span className="eyebrow">Direct contact</span><h3 className="mt-4 text-2xl font-extrabold">Send us a message</h3><p className="mt-2 text-slate-600 dark:text-[#adbfba]">Ask about products, bulk orders, store timings, or pickup.</p></div><FeedbackForm type="contact" /></div></div></section>
</main>; }
