'use client';

import { useState, type FormEvent } from 'react';

type FeedbackFormProps = { type?: 'review' | 'contact'; review?: boolean };
export default function FeedbackForm({ type = 'contact', review = false }: FeedbackFormProps) {
  const [status, setStatus] = useState(''); const [error, setError] = useState(false); const [sending, setSending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSending(true); setStatus('Sending securely...'); setError(false); const form = event.currentTarget; const payload = { ...Object.fromEntries(new FormData(form).entries()), type }; try { const response = await fetch('/api/feedback', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to send your message.'); form.reset(); setStatus(result.message); } catch (submissionError) { setError(true); setStatus(submissionError instanceof Error ? submissionError.message : 'Unable to send your message.'); } finally { setSending(false); } }
  return <form className="grid gap-3" onSubmit={submit}><div className="grid gap-3 sm:grid-cols-2"><input className="field" name="name" type="text" placeholder="Your name" required />{review ? <input className="field" name="email" type="email" placeholder="Your email (optional)" /> : <input className="field" name="phone" type="tel" placeholder="Phone number" required />}</div>{!review && <input className="field" name="email" type="email" placeholder="Your email address" required />}<textarea className="field min-h-28 resize-y" name="message" placeholder={review ? 'Write your review' : 'How can we help you?'} required /><button className="btn-primary w-fit" type="submit" disabled={sending}>{sending ? 'Sending...' : review ? '✉ Send Review' : '✉ Send Message'}</button><small className="text-xs text-slate-500 dark:text-[#adbfba]">Your message will be sent securely to gsamraj178@gmail.com.</small><p className={error ? 'text-sm font-bold text-red-700' : 'text-sm font-bold text-leaf'} role="status" aria-live="polite">{status}</p></form>;
}
